CXX = g++

SRCS := $(wildcard src/*.cpp)
OBJS := $(patsubst src/%,obj/%,$(SRCS:.cpp=.o))

INCLUDE_PATHS = -Iinclude_linux/ -I/modules/cs324/glew-1.11.0/include/
LIBRARY_PATHS = -L/modules/cs324/glew-1.11.0/lib -L/usr/X11R6/lib
COMPILER_FLAGS = -std=c++11 -O3 -c
LINKER_FLAGS = -lglut -lGL -lGLU -lX11 -lm -lGLEW -lpng

EXE_NAME = snake

all: $(EXE_NAME)

$(EXE_NAME): $(OBJS)
	$(CXX) $(LIBRARY_PATHS) -o $@ $^ $(LINKER_FLAGS)

obj/%.o: src/%.cpp
	$(CXX) $(INCLUDE_PATHS) $(COMPILER_FLAGS) -o $@ $<

clean:
	$(RM) -r obj/* ./$(EXE_NAME)
